// internal/ssl/cert_test.go
package ssl

import (
	"crypto/tls"
	"fmt"
	"path/filepath"
	"sync"
	"testing"
)

func TestCertCache_GeneratesCertForDomain(t *testing.T) {
	tmpDir := t.TempDir()
	certPath := filepath.Join(tmpDir, "ca.crt")
	keyPath := filepath.Join(tmpDir, "ca.key")

	err := GenerateCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("GenerateCA failed: %v", err)
	}

	ca, err := LoadCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("LoadCA failed: %v", err)
	}

	cache := NewCertCache(ca, "test")

	// Simulate TLS handshake
	hello := &tls.ClientHelloInfo{
		ServerName: "myapp.test",
	}

	cert, err := cache.GetCertificate(hello)
	if err != nil {
		t.Fatalf("GetCertificate failed: %v", err)
	}

	if cert.Leaf.Subject.CommonName != "*.test" {
		t.Errorf("unexpected CN: expected *.test, got %s", cert.Leaf.Subject.CommonName)
	}

	// Second call should return cached cert
	cert2, err := cache.GetCertificate(hello)
	if err != nil {
		t.Fatalf("second GetCertificate failed: %v", err)
	}

	if cert != cert2 {
		t.Error("expected same cert from cache")
	}
}

func TestCertCacheRejectsEmptySNI(t *testing.T) {
	tmpDir := t.TempDir()
	certPath := filepath.Join(tmpDir, "ca.crt")
	keyPath := filepath.Join(tmpDir, "ca.key")

	err := GenerateCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("GenerateCA failed: %v", err)
	}

	ca, err := LoadCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("LoadCA failed: %v", err)
	}

	cache := NewCertCache(ca, "test")

	// SECURITY: Empty SNI should be rejected
	hello := &tls.ClientHelloInfo{
		ServerName: "",
	}

	_, err = cache.GetCertificate(hello)
	if err == nil {
		t.Fatal("expected error for empty SNI, got nil")
	}

	expected := "SNI required"
	if got := err.Error(); len(got) < len(expected) || got[:len(expected)] != expected {
		t.Errorf("expected error containing %q, got %q", expected, got)
	}
}

func TestCertCacheConcurrentAccess(t *testing.T) {
	tmpDir := t.TempDir()
	certPath := filepath.Join(tmpDir, "ca.crt")
	keyPath := filepath.Join(tmpDir, "ca.key")

	err := GenerateCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("GenerateCA failed: %v", err)
	}

	ca, err := LoadCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("LoadCA failed: %v", err)
	}

	cache := NewCertCache(ca, "test")

	const goroutines = 50
	var wg sync.WaitGroup
	wg.Add(goroutines)

	errs := make(chan error, goroutines)

	for i := 0; i < goroutines; i++ {
		go func() {
			defer wg.Done()
			hello := &tls.ClientHelloInfo{
				ServerName: "concurrent.test",
			}
			cert, err := cache.GetCertificate(hello)
			if err != nil {
				errs <- err
				return
			}
			if cert.Leaf.Subject.CommonName != "*.test" {
				errs <- fmt.Errorf("unexpected CN: %s", cert.Leaf.Subject.CommonName)
				return
			}
		}()
	}

	wg.Wait()
	close(errs)

	for err := range errs {
		t.Errorf("concurrent GetCertificate error: %v", err)
	}
}

// TestCertCacheLRUEviction fills the cache to maxCacheSize by directly inserting
// entries, then adds one more via GetCertificate and verifies the oldest entry
// was evicted. This avoids generating 1001 real certs.
func TestCertCacheLRUEviction(t *testing.T) {
	tmpDir := t.TempDir()
	certPath := filepath.Join(tmpDir, "ca.crt")
	keyPath := filepath.Join(tmpDir, "ca.key")

	err := GenerateCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("GenerateCA failed: %v", err)
	}

	ca, err := LoadCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("LoadCA failed: %v", err)
	}

	cache := NewCertCache(ca, "test")

	// Generate one real cert to use as a placeholder for filling the cache
	hello := &tls.ClientHelloInfo{
		ServerName: "placeholder.test",
	}
	placeholderCert, err := cache.GetCertificate(hello)
	if err != nil {
		t.Fatalf("failed to generate placeholder cert: %v", err)
	}

	// Directly fill the cache to maxCacheSize by inserting fake entries.
	// We hold the lock to manipulate cache internals directly.
	cache.mu.Lock()
	// Clear the wildcard entry generated by GetCertificate above
	delete(cache.cache, "*.test")
	cache.order = cache.order[:0]

	for i := 0; i < maxCacheSize; i++ {
		name := fmt.Sprintf("domain-%04d.test", i)
		cache.cache[name] = placeholderCert
		cache.order = append(cache.order, name)
	}
	cache.mu.Unlock()

	// Verify cache is full
	cache.mu.RLock()
	if len(cache.cache) != maxCacheSize {
		t.Fatalf("expected cache size %d, got %d", maxCacheSize, len(cache.cache))
	}
	cache.mu.RUnlock()

	// The oldest entry is "domain-0000.test"
	// Now add one more entry via GetCertificate — this generates *.test wildcard
	// which should evict the oldest entry
	newHello := &tls.ClientHelloInfo{
		ServerName: "newdomain.test",
	}
	_, err = cache.GetCertificate(newHello)
	if err != nil {
		t.Fatalf("GetCertificate for new domain failed: %v", err)
	}

	// Verify cache is still at maxCacheSize (not maxCacheSize+1)
	cache.mu.RLock()
	defer cache.mu.RUnlock()

	if len(cache.cache) != maxCacheSize {
		t.Errorf("expected cache size %d after eviction, got %d", maxCacheSize, len(cache.cache))
	}

	// Verify the oldest entry was evicted
	if _, ok := cache.cache["domain-0000.test"]; ok {
		t.Error("expected oldest entry 'domain-0000.test' to be evicted, but it still exists")
	}

	// Verify the wildcard entry exists (replaces per-domain entries)
	if _, ok := cache.cache["*.test"]; !ok {
		t.Error("expected wildcard entry '*.test' to exist in cache")
	}

	// Verify a non-evicted entry still exists
	if _, ok := cache.cache["domain-0001.test"]; !ok {
		t.Error("expected 'domain-0001.test' to still exist in cache")
	}
}

func TestWildcardCertCoversSubdomains(t *testing.T) {
	tmpDir := t.TempDir()
	certPath := filepath.Join(tmpDir, "ca.crt")
	keyPath := filepath.Join(tmpDir, "ca.key")

	err := GenerateCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("GenerateCA failed: %v", err)
	}

	ca, err := LoadCA(certPath, keyPath)
	if err != nil {
		t.Fatalf("LoadCA failed: %v", err)
	}

	cache := NewCertCache(ca, "test")

	// First request generates wildcard cert
	cert1, err := cache.GetCertificate(&tls.ClientHelloInfo{ServerName: "app1.test"})
	if err != nil {
		t.Fatal(err)
	}

	// Second request for different subdomain returns same cert
	cert2, err := cache.GetCertificate(&tls.ClientHelloInfo{ServerName: "app2.test"})
	if err != nil {
		t.Fatal(err)
	}

	// Should be the exact same cert object
	if cert1 != cert2 {
		t.Error("expected same wildcard cert for different subdomains")
	}

	// Verify the cert covers wildcard
	if cert1.Leaf == nil {
		t.Fatal("expected parsed leaf")
	}
	foundWildcard := false
	foundBare := false
	for _, dns := range cert1.Leaf.DNSNames {
		if dns == "*.test" {
			foundWildcard = true
		}
		if dns == "test" {
			foundBare = true
		}
	}
	if !foundWildcard {
		t.Errorf("expected *.test in DNSNames, got %v", cert1.Leaf.DNSNames)
	}
	if !foundBare {
		t.Errorf("expected bare 'test' in DNSNames, got %v", cert1.Leaf.DNSNames)
	}
}
