linters:
  disable:
    - errcheck  # Too strict for simple CLI tools
  enable:
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  govet:
    disable:
      - fieldalignment
      - shadow
