//go:build darwin

// internal/setup/setup_darwin.go
package setup

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/alexcatdad/paw-proxy/internal/ssl"
)

type Config struct {
	SupportDir string
	BinaryPath string
	DNSPort    int
	TLD        string
}

func Run(config *Config) error {
	fmt.Println("paw-proxy setup")
	fmt.Println("================")

	// 1. Create support directory
	fmt.Printf("\n[1/5] Creating support directory...\n")
	if err := os.MkdirAll(config.SupportDir, 0700); err != nil {
		return fmt.Errorf("creating support dir: %w", err)
	}
	fmt.Printf("  ✓ %s\n", config.SupportDir)

	// 2. Generate CA
	fmt.Printf("\n[2/5] Generating CA certificate...\n")
	certPath := filepath.Join(config.SupportDir, "ca.crt")
	keyPath := filepath.Join(config.SupportDir, "ca.key")

	if _, err := os.Stat(certPath); err == nil {
		fmt.Printf("  ✓ CA already exists\n")
	} else {
		if err := ssl.GenerateCA(certPath, keyPath); err != nil {
			return fmt.Errorf("generating CA: %w", err)
		}
		fmt.Printf("  ✓ Generated CA certificate\n")
	}

	// 3. Trust CA in keychain
	fmt.Printf("\n[3/5] Adding CA to keychain...\n")
	fmt.Printf("  Note: You may be prompted for your password\n")
	if err := trustCA(certPath); err != nil {
		return fmt.Errorf("trusting CA: %w", err)
	}
	fmt.Printf("  ✓ CA trusted in login keychain\n")

	// 4. Create resolver file
	fmt.Printf("\n[4/5] Configuring DNS resolver...\n")
	if err := configureResolver(config.TLD, config.DNSPort); err != nil {
		return fmt.Errorf("configuring resolver: %w", err)
	}
	fmt.Printf("  ✓ /etc/resolver/%s created\n", config.TLD)

	// 5. Install LaunchAgent
	fmt.Printf("\n[5/5] Installing daemon...\n")
	if err := installLaunchAgent(config); err != nil {
		return fmt.Errorf("installing LaunchAgent: %w", err)
	}
	fmt.Printf("  ✓ LaunchAgent installed and started\n")

	fmt.Println("\n================")
	fmt.Println("Setup complete!")
	fmt.Println("")
	fmt.Println("Note: macOS may show a 'Background Items Added' notification. This is normal.")
	fmt.Println("")
	fmt.Println("Firefox users: Install 'nss' for certificate trust:")
	fmt.Println("  brew install nss")
	fmt.Println("  paw-proxy setup  (re-run to update Firefox)")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  up bun dev           # Start dev server with HTTPS")
	fmt.Println("  up -n myapp npm start # Custom domain name")

	return nil
}

func trustCA(certPath string) error {
	// Try login keychain first (works for normal user sessions)
	if out, err := exec.Command("security", "login-keychain").Output(); err == nil {
		keychain := strings.TrimSpace(strings.Trim(string(out), `"`))
		cmd := exec.Command("security", "add-trusted-cert", "-k", keychain, certPath)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if cmd.Run() == nil {
			return nil
		}
	}

	// Fall back to System keychain (CI/headless/root environments)
	cmd := exec.Command("security", "add-trusted-cert", "-d", "-r", "trustRoot",
		"-k", "/Library/Keychains/System.keychain", certPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func configureResolver(tld string, port int) error {
	resolverDir := "/etc/resolver"
	if err := os.MkdirAll(resolverDir, 0755); err != nil {
		return err
	}

	content := fmt.Sprintf("# Generated by paw-proxy\nnameserver 127.0.0.1\nport %d\n", port)
	path := filepath.Join(resolverDir, tld)

	return os.WriteFile(path, []byte(content), 0644)
}

var launchAgentTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>dev.paw-proxy</string>
    <key>ProgramArguments</key>
    <array>
        <string>{{.BinaryPath}}</string>
        <string>run</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>Sockets</key>
    <dict>
        <key>http</key>
        <dict>
            <key>SockNodeName</key>
            <string>127.0.0.1</string>
            <key>SockServiceName</key>
            <string>80</string>
        </dict>
        <key>https</key>
        <dict>
            <key>SockNodeName</key>
            <string>127.0.0.1</string>
            <key>SockServiceName</key>
            <string>443</string>
        </dict>
    </dict>
</dict>
</plist>
`

func installLaunchAgent(config *Config) error {
	homeDir, _ := os.UserHomeDir()
	plistDir := filepath.Join(homeDir, "Library", "LaunchAgents")
	plistPath := filepath.Join(plistDir, "dev.paw-proxy.plist")

	if err := os.MkdirAll(plistDir, 0755); err != nil {
		return err
	}

	// Unload existing if present
	exec.Command("launchctl", "unload", plistPath).Run()

	// Write plist
	f, err := os.Create(plistPath)
	if err != nil {
		return err
	}
	defer f.Close()

	tmpl, err := template.New("plist").Parse(launchAgentTemplate)
	if err != nil {
		return err
	}

	if err := tmpl.Execute(f, config); err != nil {
		return err
	}

	// Load plist
	return exec.Command("launchctl", "load", plistPath).Run()
}
